{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bg-express-api.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "bg-express-api.name" . }}
    chart: {{ template "bg-express-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  {{- range $spec := .Values.ingress.spec }}
  ingressClassName: {{ $spec.ingressClassName }}
  {{- end }}
  rules:
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host.name }}
    http:
      paths:
      {{- range $paths := $host.paths}}
        - path: {{ $paths.pathUrl}}
          pathType: Prefix
          backend:
            service:
              name: {{ $paths.serviceName }}
              port:
                number: {{ $paths.servicePort }}
      {{- end }}
  {{- end }}
{{- end }}
